name: Sync CaC content to OSCAL
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  check-pr-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the PR comes from the sync of OSCAL content
      run: |
        if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          echo "PR Title: $PR_TITLE"
          echo "PR Body: $PR_BODY"

          if [[ "$PR_TITLE" == *"Automatic updates from OSCAL content"* ]] || [[ "$PR_BODY" == *"Automatic updates from OSCAL content"* ]]; then
            echo "The PR comes from OSCAL content. The task of Sync CaC content to OSCAL will exit."
            echo "Skipping further checks."
          else
            echo "Start to check the content updates"
          fi
        else
          echo "The PR is not merged. Skipping further checks."
        fi

