name: Sync CaC content to OSCAL
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  check-pr-message:
    runs-on: ubuntu-latest
    outputs:
      run_job_check_update: ${{ steps.check_pr.outputs.run_job_check_update }}
    steps:
    - name: Check if the PR comes from the sync of OSCAL content
      id: check_pr
      run: |
        if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

            echo "PR Title: $PR_TITLE"
            echo "PR Body: $PR_BODY"
          if [[ "$PR_TITLE" == *"Automatic updates from OSCAL content"* ]] || [[ "$PR_BODY" == *"Automatic updates from OSCAL content"* ]]; then
            echo "The PR comes from OSCAL content. The task of Sync CaC content to OSCAL will exit."
            echo "Skipping further checks."
            exit 0
          else
            echo "::set-output name=run_job_check_update::true"
          fi
         fi
  check-cac-content-update:
    runs-on: ubuntu-latest
    needs: check-pr-message
    if: ${{ needs.check-pr-message.outputs.run_job_check_update == 'true' }}
    steps:
      # Step 1: Set up Python 3
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 2: Install Git (if not already installed)
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install gitpython PyYAML deepdiff Jinja2 xmldiff

      # Step 4: Checkout the ComplianceAsCode/content-test-filtering repository
      - name: Checkout (CTF)
        uses: actions/checkout@v4  # Use the latest version of actions/checkout
        with:
          repository: ComplianceAsCode/content-test-filtering
          path: ctf
      # Step 5: Detect content changes in the PR
      - name: Detect content changes in the PR
        run: |
          python ctf/content_test_filtering.py pr \
            --base d2d1faf6db138f649c235af0f701cdfc110a3ffb \
            --remote_repo https://github.com/ComplianceAsCode/content \
            --verbose --profile --rule --output json 13176 > output.json