name: Sync CaC content to OSCAL
on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  check-pr-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the PR comes from the sync of OSCAL content
      run: |
        if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"

          echo "PR Title: $PR_TITLE"
          echo "PR Body: $PR_BODY"

          if [[ "$PR_TITLE" == *"Automatic updates from OSCAL content"* ]] || [[ "$PR_BODY" == *"Automatic updates from OSCAL content"* ]]; then
            echo "The PR comes from OSCAL content. The task of Sync CaC content to OSCAL will exit."
            echo "Skipping further checks."
            exit 0
          else
            echo "Start to check the content updates"
              echo "check_content_update=true" >> $GITHUB_ENV
          fi
        fi

  check-cac-content-update:
    runs-on: ubuntu-latest
    needs: check-pr-message
    if: ${{ env.check_content_update == 'true' }}
    steps:
      - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install gitpython PyYAML deepdiff Jinja2 xmldiff
      - name: Checkout (CTF)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          repository: ComplianceAsCode/content-test-filtering
          path: ctf
      - name: Detect content changes in the PR
        run: python content_test_filtering.py pr --base d2d1faf6db138f649c235af0f701cdfc110a3ffb --remote_repo https://github.com/ComplianceAsCode/content --verbose --profile --rule  --output json 13176 > output.json
